# Version 0.0.2

FROM postgres:9.4

MAINTAINER Alex Mcknight <mcknight816@gmail.com>

ENV DB_NAME sensei
ENV DB_USER postgres
ENV DB_PASS Stud1o4465

ADD setupRemoteConnections.sh /docker-entrypoint-initdb.d/setupRemoteConnections.sh
RUN chmod 755 /docker-entrypoint-initdb.d/setupRemoteConnections.sh
ADD setup-database.sh /docker-entrypoint-initdb.d/
RUN chmod 755 /docker-entrypoint-initdb.d/setup-database.sh